import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createLoopExtension, parseLoopCommand } from "../resources/coco-loop.mjs";

function memoryStore({ load } = {}) { let state = { revision: 0, schemaVersion: 1, tasks: [] }; return { load: async () => { if (load) await load(); return structuredClone(state); }, update: async (change) => { state = await change(structuredClone(state)); state.revision += 1; return structuredClone(state); }, state: () => structuredClone(state) }; }
function harness({ clock = 0, store = memoryStore(), send } = {}) { const commands = new Map(); const events = new Map(); const sent = []; const timers = []; const cleared = []; const time = { value: clock }; const api = { on: (name, handler) => events.set(name, handler), registerCommand: (name, value) => commands.set(name, value), registerTool: (value) => { api.tool = value; }, sendUserMessage: (text, options) => send ? send(text, options) : sent.push({ options, text }), sendMessage: (message, options) => send ? send(message.content, options) : sent.push({ options, text: message.content }) }; const extension = createLoopExtension({ now: () => time.value, randomId: (() => { let n = 0; return () => `abcdefg${n++}`; })(), setTimeoutFn: (callback) => { timers.push(callback); return timers.length; }, clearTimeoutFn: (id) => cleared.push(id), store }); extension(api); const context = { hasUI: true, isIdle: true, sessionManager: { getSessionFile: () => "/tmp/a.jsonl" }, ui: { notify: () => {}, setStatus: () => {} } }; return { api, cleared, commands, context, events, sent, store, time, timers }; }
const tick = () => new Promise((resolve) => setImmediate(resolve));

test("loop parser accepts fixed and dynamic public grammar", () => { assert.deepEqual(parseLoopCommand(""), { type: "list" }); assert.deepEqual(parseLoopCommand("5m check deploy"), { dynamic: false, intervalMs: 300000, prompt: "check deploy", type: "create" }); assert.deepEqual(parseLoopCommand("check deploy every 2 hours"), { dynamic: false, intervalMs: 7200000, prompt: "check deploy", type: "create" }); assert.deepEqual(parseLoopCommand("check"), { dynamic: true, intervalMs: 600000, prompt: "check", type: "create" }); assert.equal(parseLoopCommand("10s").intervalMs, 60000); });
test("idle timer dispatches directly while busy timer waits and follows up after settlement", async () => { const idle = harness(); await idle.events.get("session_start")({}, idle.context); await idle.commands.get("loop").handler("5m check", idle.context); idle.time.value = 300000; idle.timers.at(-1)(); await tick(); assert.equal(idle.sent.length, 1); const busy = harness(); await busy.events.get("session_start")({}, busy.context); await busy.commands.get("loop").handler("5m check", busy.context); busy.context.isIdle = false; busy.time.value = 300000; busy.timers.at(-1)(); await tick(); assert.equal(busy.sent.length, 0); busy.context.isIdle = true; await busy.events.get("agent_settled")({}, busy.context); assert.equal(busy.sent.length, 1); });
test("timers are cleared and stale arms cannot replace a session switch or shutdown", async () => { let release; const store = memoryStore({ load: () => new Promise((resolve) => { release = resolve; }) }); const h = harness({ store }); const start = h.events.get("session_start")({}, h.context); await tick(); const shutdown = h.events.get("session_shutdown")({}, h.context); release(); await Promise.all([start, shutdown]); assert.equal(h.timers.length, 0); assert.ok(h.cleared.length >= 0); });
test("live expiry fires once, resume expiry is silent, and missed work does not catch up", async () => { const live = harness(); await live.events.get("session_start")({}, live.context); await live.commands.get("loop").handler("5m check", live.context); live.time.value = 7 * 86400000; live.timers.at(-1)(); await tick(); assert.equal(live.sent.length, 1); assert.equal(live.store.state().tasks.length, 0); const resumeStore = memoryStore(); const resume = harness({ clock: 7 * 86400000, store: resumeStore }); await resumeStore.update((state) => { state.tasks.push({ createdAt: new Date(0).toISOString(), dynamic: false, expiresAt: new Date(7 * 86400000).toISOString(), fallbacks: 0, id: "abcdefgh", intervalMs: 60000, nextDueAt: new Date(60000).toISOString(), prompt: "check", sessionFile: "/tmp/a.jsonl" }); return state; }); await resume.events.get("session_start")({}, resume.context); assert.equal(resume.sent.length, 0); assert.equal(resumeStore.state().tasks.length, 0); });
test("dynamic tasks serialize and reject stale wakeup calls", async () => { const h = harness(); await h.events.get("session_start")({}, h.context); await h.commands.get("loop").handler("first", h.context); await h.commands.get("loop").handler("second", h.context); h.time.value = 600000; h.timers.at(-1)(); await tick(); assert.equal(h.sent.length, 1); const stale = await h.api.tool.execute("id", { action: "stop", taskId: "wrong" }); assert.equal(stale.isError, true); const ok = await h.api.tool.execute("id", { action: "reschedule", delay: "5m", reason: "working", taskId: "abcdefg0" }); assert.equal(ok.isError, undefined); h.timers.at(-1)(); await tick(); assert.equal(h.sent.length, 2); });
test("failed synchronous sends retain work and retry without advancing", async () => { let fail = true; let accepted = 0; const h = harness({ send: () => { if (fail) throw new Error("send"); accepted += 1; } }); await h.events.get("session_start")({}, h.context); await h.commands.get("loop").handler("5m check", h.context); h.time.value = 300000; h.timers.at(-1)(); await tick(); assert.equal(h.store.state().tasks[0].nextDueAt, new Date(300000).toISOString()); fail = false; h.timers.at(-1)(); await tick(); assert.equal(accepted, 1); assert.equal(h.store.state().tasks[0].nextDueAt, new Date(600000).toISOString()); });
test("invalid global loop.md falls back to the built-in prompt", async () => { const previous = process.env.COCO_CODING_AGENT_DIR; const directory = await mkdtemp(join(tmpdir(), "coco-loop-prompt-")); process.env.COCO_CODING_AGENT_DIR = directory; try { await writeFile(join(directory, "loop.md"), "invalid\u0000prompt"); const h = harness(); await h.events.get("session_start")({}, h.context); await h.commands.get("loop").handler("5m", h.context); h.time.value = 300000; h.timers.at(-1)(); await new Promise((resolve) => setTimeout(resolve, 25)); assert.match(h.sent[0].text, /Continue transcript-authorized/); } finally { if (previous === undefined) delete process.env.COCO_CODING_AGENT_DIR; else process.env.COCO_CODING_AGENT_DIR = previous; } });
test("loop source contains no child process or network capability", async () => { const source = await import("node:fs/promises").then(({ readFile }) => readFile(new URL("../resources/coco-loop.mjs", import.meta.url), "utf8")); assert.doesNotMatch(source, /child_process|https?:\/\//); });
