import { constants } from "node:fs";
import { lstat, open } from "node:fs/promises";
import { join } from "node:path";
import { createLoopStateStore, loopAgentDirectory, loopId } from "../scripts/loop-state.mjs";
import { translate } from "./coco-language.mjs";

const MINUTE = 60000; const DAY = 86400000; const MAX_DELAY = 0x7fffffff; const RETRY_DELAY = 1000;
const DEFAULT_PROMPT = "Continue transcript-authorized unfinished work; tend the current branch PR, CI, and review conflicts; run cleanup if idle; do not start unrelated initiatives; irreversible actions require prior authorization.";
const duration = (value) => { const match = /^(\d+)\s*(seconds?|minutes?|hours?|days?|[smhd])$/i.exec(value.trim()); if (!match) return null; const ms = Number(match[1]) * ({ s: 1000, m: MINUTE, h: 3600000, d: DAY }[match[2].toLowerCase()[0]]); return Number.isSafeInteger(ms) && ms > 0 ? Math.max(MINUTE, Math.ceil(ms / MINUTE) * MINUTE) : null; };
export function parseLoopCommand(argument) { const input = String(argument ?? "").trim(); if (input === "" || input === "list" || input === "status") return { type: "list" }; const cancel = /^cancel\s+([A-Za-z0-9_-]{1,8})$/i.exec(input); if (cancel) return { id: cancel[1], type: "cancel" }; const every = /^(.*?)\s+every\s+(.+)$/i.exec(input); if (every) { const intervalMs = duration(every[2]); if (!intervalMs) throw new Error("LOOP_DURATION_INVALID"); return { dynamic: false, intervalMs, prompt: every[1].trim() || null, type: "create" }; } const leading = /^(\d+\s*(?:[smhd]|seconds?|minutes?|hours?|days?))(?:\s+(.*))?$/i.exec(input); if (leading) { const intervalMs = duration(leading[1]); if (!intervalMs) throw new Error("LOOP_DURATION_INVALID"); return { dynamic: false, intervalMs, prompt: leading[2]?.trim() || null, type: "create" }; } return { dynamic: true, intervalMs: 10 * MINUTE, prompt: input, type: "create" }; }
function validPrompt(prompt) { return prompt === null || (typeof prompt === "string" && prompt.length > 0 && Buffer.byteLength(prompt) <= 25000 && !/[\0-\x1f\x7f]/.test(prompt)); }
async function defaultPrompt() { const path = join(loopAgentDirectory(), "loop.md"); try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink() || info.size === 0 || info.size > 25000) return DEFAULT_PROMPT; const descriptor = await open(path, constants.O_RDONLY | (process.platform === "win32" ? 0 : (constants.O_NOFOLLOW ?? 0))); try { const text = await descriptor.readFile("utf8"); return text && !/[\0-\x1f\x7f]/.test(text) ? text : DEFAULT_PROMPT; } finally { await descriptor.close(); } } catch { return DEFAULT_PROMPT; } }

export function createLoopExtension({ store = createLoopStateStore(), now = Date.now, setTimeoutFn = setTimeout, clearTimeoutFn = clearTimeout, randomId = loopId, t = translate } = {}) { return function cocoLoop(pi) {
  let timer = null; let sessionFile = null; let ctx = null; let stopped = false; let pending = null; let awaitingId = null; let epoch = 0; let scheduler = Promise.resolve();
  const notify = (message, level = "info") => { if (ctx?.hasUI) ctx.ui.notify(message, level); };
  const enqueue = (operation) => { const result = scheduler.then(operation, operation); scheduler = result.catch(() => {}); return result; };
  const stopTimer = () => { if (timer !== null) clearTimeoutFn(timer); timer = null; };
  const advance = (task, current) => { while (Date.parse(task.nextDueAt) <= current) task.nextDueAt = new Date(Date.parse(task.nextDueAt) + task.intervalMs).toISOString(); };
  const queued = () => !ctx?.isIdle || Boolean(ctx?.hasPendingMessages?.() || ctx?.pendingMessages?.length);
  async function arm(token = epoch) { stopTimer(); if (stopped || !sessionFile || token !== epoch) return; const activeSession = sessionFile; const state = await store.load(); if (stopped || token !== epoch || sessionFile !== activeSession) return; const next = state.tasks.filter((x) => x.sessionFile === activeSession && x.id !== awaitingId && x.id !== pending?.id).reduce((best, x) => Math.min(best, Date.parse(x.nextDueAt), Date.parse(x.expiresAt)), Infinity); if (Number.isFinite(next)) timer = setTimeoutFn(() => { timer = null; void enqueue(async () => { if (token !== epoch) return; await ready(token, true); if (!queued()) await dispatch(token); }); }, Math.max(0, Math.min(MAX_DELAY, next - now()))); }
  async function ready(token = epoch, live = true) { if (pending || awaitingId || stopped || !sessionFile || token !== epoch) return; const current = now(); const activeSession = sessionFile; let selected; await store.update((state) => { for (const task of state.tasks) { if (task.sessionFile !== activeSession || selected) continue; const expires = Date.parse(task.expiresAt); if ((!live && expires <= current)) continue; if (expires <= current || Date.parse(task.nextDueAt) <= current) selected = structuredClone(task); } state.tasks = state.tasks.filter((task) => task.sessionFile !== activeSession || task.id === selected?.id || Date.parse(task.expiresAt) >= current); return state; }); if (stopped || token !== epoch || sessionFile !== activeSession) return; if (selected) pending = { ...selected, expiry: Date.parse(selected.expiresAt) <= current }; await arm(token); }
  async function dispatch(token = epoch) { if (!pending || stopped || token !== epoch || !sessionFile) return false; const task = pending; const prompt = task.prompt ?? await defaultPrompt(); if (stopped || token !== epoch || pending !== task) return false; try { const message = { content: prompt, customType: "coco-loop-wakeup-v1", display: true, details: { taskId: task.id } }; const result = pi.sendUserMessage ? pi.sendUserMessage(prompt, queued() ? { deliverAs: "followUp" } : undefined) : pi.sendMessage(message, { triggerTurn: true, ...(queued() ? { deliverAs: "followUp" } : {}) }); if (result && typeof result.then === "function") await result; } catch { stopTimer(); if (!stopped && token === epoch && pending === task) timer = setTimeoutFn(() => { timer = null; void enqueue(() => dispatch(token)); }, RETRY_DELAY); return false; } if (stopped || token !== epoch || pending !== task) return false; pending = null; if (task.dynamic) awaitingId = task.id; else await store.update((state) => { const saved = state.tasks.find((x) => x.id === task.id && x.sessionFile === sessionFile); if (saved) { if (task.expiry) state.tasks = state.tasks.filter((x) => x !== saved); else advance(saved, now()); } return state; }); await arm(token); return true; }
  async function settle(token = epoch) { if (!awaitingId || stopped || token !== epoch || !sessionFile) return; const id = awaitingId; awaitingId = null; await store.update((state) => { const task = state.tasks.find((x) => x.id === id && x.sessionFile === sessionFile && x.dynamic); if (task) { task.fallbacks += 1; if (task.fallbacks >= 2) state.tasks = state.tasks.filter((x) => x !== task); else task.nextDueAt = new Date(now() + 20 * MINUTE).toISOString(); } return state; }); await ready(token); await arm(token); }
  async function reload(eventCtx, token) { if (token !== epoch) return; stopped = false; pending = null; awaitingId = null; ctx = eventCtx; sessionFile = ctx?.sessionManager?.getSessionFile?.() ?? null; if (!sessionFile) return; const activeSession = sessionFile; const current = now(); await store.update((state) => { for (const task of state.tasks) if (task.sessionFile === activeSession && Date.parse(task.expiresAt) > current && Date.parse(task.nextDueAt) <= current) advance(task, current); state.tasks = state.tasks.filter((task) => task.sessionFile !== activeSession || Date.parse(task.expiresAt) > current); return state; }); if (token === epoch && sessionFile === activeSession && !stopped) await arm(token); }
  pi.registerCommand("loop", { description: t("loop.commandDescription"), handler: async (argument, commandCtx) => { ctx = commandCtx; try { const action = parseLoopCommand(argument); if (action.type === "list") { const tasks = (await store.load()).tasks.filter((x) => x.sessionFile === sessionFile); notify(tasks.length ? tasks.map((x) => `${x.id} ${x.dynamic ? "dynamic" : `${x.intervalMs / MINUTE}m`} ${x.nextDueAt}`).join("\n") : t("loop.empty")); return; } if (!sessionFile) throw new Error("LOOP_SESSION_REQUIRED"); if (action.type === "create") { if (!validPrompt(action.prompt)) throw new Error("LOOP_PROMPT_INVALID"); const createdAt = new Date(now()).toISOString(); let task; await store.update((state) => { if (state.tasks.filter((x) => x.sessionFile === sessionFile).length >= 50) throw new Error("LOOP_LIMIT_REACHED"); task = { id: randomId(), sessionFile, prompt: action.prompt, intervalMs: action.intervalMs, dynamic: action.dynamic, fallbacks: 0, createdAt, expiresAt: new Date(now() + 7 * DAY).toISOString(), nextDueAt: new Date(now() + action.intervalMs).toISOString() }; state.tasks.push(task); return state; }); notify(t("loop.created", { id: task.id })); await enqueue(() => arm()); return; } let removed; await store.update((state) => { const matches = state.tasks.filter((x) => x.sessionFile === sessionFile && x.id.startsWith(action.id)); if (!matches.length) throw new Error("LOOP_NOT_FOUND"); if (matches.length > 1) throw new Error("LOOP_AMBIGUOUS_ID"); removed = matches[0]; state.tasks = state.tasks.filter((x) => x !== removed); return state; }); notify(t("loop.cancelled", { id: removed.id })); await enqueue(() => arm()); } catch (error) { notify(t(`loop.error.${error instanceof Error ? error.message : "LOOP_FAILED"}`), "error"); } } });
  pi.registerTool({ name: "loop_wakeup", label: "Loop wakeup", description: "Reschedule or stop the dynamic loop task awaiting this session turn.", parameters: { additionalProperties: false, properties: { action: { enum: ["reschedule", "stop"] }, delay: { type: "string" }, reason: { type: "string" }, taskId: { type: "string" } }, required: ["action", "taskId"], type: "object" }, async execute(_id, value) { try { let result; await enqueue(async () => { const id = awaitingId; if (!id || value.taskId !== id || !sessionFile) throw new Error("LOOP_NOT_AWAITING"); await store.update((state) => { const task = state.tasks.find((x) => x.id === id && x.sessionFile === sessionFile && x.dynamic); if (!task) throw new Error("LOOP_NOT_AWAITING"); if (value.action === "stop") { state.tasks = state.tasks.filter((x) => x !== task); result = "stopped"; } else { const delay = duration(value.delay ?? ""); if (!delay || delay > 3600000 || typeof value.reason !== "string" || !value.reason.trim()) throw new Error("LOOP_WAKEUP_INVALID"); task.nextDueAt = new Date(now() + delay).toISOString(); task.fallbacks = 0; result = `scheduled for ${task.nextDueAt}`; } awaitingId = null; return state; }); await arm(); }); return { content: [{ type: "text", text: result }] }; } catch (error) { return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true }; } } });
  const beginReload = (eventCtx) => { const token = ++epoch; stopTimer(); return enqueue(() => reload(eventCtx, token)); };
  pi.on("session_start", async (_event, eventCtx) => beginReload(eventCtx)); pi.on("session_tree", async (_event, eventCtx) => beginReload(eventCtx)); pi.on("agent_settled", async () => enqueue(async () => { if (await dispatch()) return; await settle(); if (!queued()) await dispatch(); })); pi.on("session_shutdown", async (_event, eventCtx) => { epoch += 1; stopped = true; stopTimer(); pending = null; awaitingId = null; sessionFile = null; ctx = null; return enqueue(async () => { if (eventCtx?.hasUI) eventCtx.ui.setStatus("coco-loop", undefined); }); });
}; }
export default createLoopExtension();
