import { randomBytes } from "node:crypto";
import { constants } from "node:fs";
import { chmod, lstat, mkdir, open, readFile, rename, unlink } from "node:fs/promises";
import { homedir } from "node:os";
import { basename, join, resolve } from "node:path";

const MAX_TASKS = 5000; const MAX_PROMPT = 25000; const MAX_PATH = 4096; const ID = /^[A-Za-z0-9_-]{8}$/;
const iso = (value) => typeof value === "string" && Number.isFinite(Date.parse(value));
const object = (value) => value !== null && typeof value === "object" && !Array.isArray(value);
const fail = (code) => { const error = new Error(code); error.code = code; throw error; };
const noFollow = process.platform === "win32" ? 0 : (constants.O_NOFOLLOW ?? 0);

export function loopAgentDirectory(environment = process.env) { return resolve(environment.COCO_CODING_AGENT_DIR || join(environment.HOME || homedir(), ".coco", "agent")); }
export function emptyLoopState() { return { revision: 0, schemaVersion: 1, tasks: [] }; }
export function loopId(random = randomBytes) { return random(6).toString("base64url"); }
function validTask(task) { return object(task) && Object.keys(task).length === 9 && ID.test(task.id) && typeof task.sessionFile === "string" && task.sessionFile.length > 0 && task.sessionFile.length <= MAX_PATH && (task.prompt === null || (typeof task.prompt === "string" && task.prompt.length > 0 && Buffer.byteLength(task.prompt) <= MAX_PROMPT && !/[\0-\x1f\x7f]/.test(task.prompt))) && Number.isSafeInteger(task.intervalMs) && task.intervalMs >= 60000 && task.intervalMs <= 86400000 && typeof task.dynamic === "boolean" && Number.isSafeInteger(task.fallbacks) && task.fallbacks >= 0 && task.fallbacks <= 2 && iso(task.createdAt) && iso(task.expiresAt) && iso(task.nextDueAt) && Date.parse(task.expiresAt) - Date.parse(task.createdAt) === 7 * 86400000; }
export function validLoopState(value) { return object(value) && Object.keys(value).length === 3 && value.schemaVersion === 1 && Number.isSafeInteger(value.revision) && value.revision >= 0 && Array.isArray(value.tasks) && value.tasks.length <= MAX_TASKS && value.tasks.every(validTask) && new Set(value.tasks.map((task) => task.id)).size === value.tasks.length && [...new Set(value.tasks.map((task) => task.sessionFile))].every((sessionFile) => value.tasks.filter((task) => task.sessionFile === sessionFile).length <= 50); }

export function createLoopStateStore({ agentDir = loopAgentDirectory(), random = randomBytes } = {}) {
  const directory = resolve(agentDir); const path = join(directory, "loops.json"); const lock = join(directory, "loops.lock"); let queue = Promise.resolve();
  async function secureDirectory() { await mkdir(directory, { mode: 0o700, recursive: true }); const info = await lstat(directory); if (!info.isDirectory() || info.isSymbolicLink()) fail("LOOP_STATE_DIRECTORY_INVALID"); if (process.platform !== "win32") { await chmod(directory, 0o700); if (((await lstat(directory)).mode & 0o777) !== 0o700) fail("LOOP_STATE_PERMISSION_INVALID"); } }
  async function read() { await secureDirectory(); try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink()) fail("LOOP_STATE_ENTRY_INVALID"); if (process.platform !== "win32" && (info.mode & 0o777) !== 0o600) fail("LOOP_STATE_PERMISSION_INVALID"); const descriptor = await open(path, constants.O_RDONLY | noFollow); try { const state = JSON.parse(await descriptor.readFile("utf8")); if (!validLoopState(state)) fail("LOOP_STATE_INVALID"); return state; } finally { await descriptor.close(); } } catch (error) { if (error?.code === "ENOENT") return emptyLoopState(); throw error; } }
  async function acquireLock() { for (let attempt = 0; attempt < 100; attempt += 1) { try { const descriptor = await open(lock, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | noFollow, 0o600); try { await descriptor.writeFile(`${process.pid}\n`); await descriptor.sync(); } finally { await descriptor.close(); } return; } catch (error) { if (error?.code !== "EEXIST") throw error; const info = await lstat(lock); if (!info.isFile() || info.isSymbolicLink()) fail("LOOP_STATE_LOCK_INVALID"); let owner; try { owner = Number((await readFile(lock, "utf8")).trim()); } catch { fail("LOOP_STATE_LOCK_INVALID"); } if (!Number.isSafeInteger(owner) || owner < 1) fail("LOOP_STATE_LOCK_INVALID"); try { process.kill(owner, 0); } catch (ownerError) { if (ownerError?.code === "ESRCH") { try { await unlink(lock); } catch {} } } await new Promise((resolve) => setTimeout(resolve, 10)); } } fail("LOOP_STATE_LOCK_TIMEOUT"); }
  async function write(state) { if (!validLoopState(state)) fail("LOOP_STATE_INVALID"); try { const info = await lstat(path); if (!info.isFile() || info.isSymbolicLink()) fail("LOOP_STATE_ENTRY_INVALID"); } catch (error) { if (error?.code !== "ENOENT") throw error; } const temporary = join(directory, `.${basename(path)}.${loopId(random)}.tmp`); const descriptor = await open(temporary, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | noFollow, 0o600); try { await descriptor.writeFile(`${JSON.stringify(state)}\n`); await descriptor.sync(); } finally { await descriptor.close(); } await rename(temporary, path); if (process.platform !== "win32") await chmod(path, 0o600); }
  function serialized(operation) { const result = queue.then(operation, operation); queue = result.catch(() => {}); return result; }
  return { path, load: () => serialized(read), update: (change) => serialized(async () => { await secureDirectory(); await acquireLock(); try { const current = await read(); const next = await change(structuredClone(current)); if (!validLoopState(next)) fail("LOOP_STATE_INVALID"); next.revision = current.revision + 1; await write(next); return structuredClone(next); } finally { try { await unlink(lock); } catch {} } }) };
}
